version: 0.1

phases:
    install:
        commands:
            - npm install
    build:
        commands:
            - echo building fixmyjs...
            - npm run build
            - echo build finished
    post_build:
        commands:
            - npm test
            - echo syncing with S3...
            - aws s3 sync ./ s3://ngdeployv2/development
